### ISSUE TITLE
Question? interfacing with windows

### ISSUE THREAD

**Issue by aastorg2** [SaswatPadhi/LoopInvGen#6]
Hello Saswat,

I tried to build the ocaml code in Cygwin but the command 

opam install core.v0.11.2 fails.
[ERROR] core.v0.11.2 is not available because your system doesn't comply with
        ocaml-version >= "4.04.1" & os != "win32"

I suppose I cannot build this tool in windows? 

I would like to interface with the function that learns boolean formulas. https://github.com/SaswatPadhi/LoopInvGen/blob/master/src/BFL.ml#L198

Do you think it is possible to do this from windows?

**Comment by SaswatPadhi** [comment]
Hello,

Unfortunately the core library from JaneStreet is not available for Windows, so you would not be able to build our tool because of this missing dependency.

However, instead of building within Cygwin, another possible approach could be to run a docker container instead. I haven't tried this, but something like this should work:
- Within the docker container, edit the source files as necessary, to expose the boolean function learner, then recompile
- From Windows cmd, run a `[command]` within the docker container directly using `docker exec -it [container id] [command]`

Would this work for your case?

**Comment by aastorg2** [comment]
thanks! 
I need to interact with the BFL function in rounds.  I think this will do. I will try it.

Additionally, does your approach support numerical predicates? and if so, is the feature synthesizer responsible for choosing a numerical constant value?  for example, if the target formula is  
(value > 10 || A || B) && (...), I assume the synthesizer will output 'value > 10' ? and the BFL function will take this as input to produce the target formula. Is this correct?

**Comment by SaswatPadhi** [comment]
Great! If there is anything I can provide within LoopInvGen (may be expose some specific API) that would be useful to you, please let me know.

Also, it just occurred to me that if all you require is the `BFL` module, then you could also just copy the file itself (and the `CNF.ml` file). Unlike the other modules, these two modules make minimal use of JaneStreet's `Core` and `Base` and so it should be very easy to completely remove the dependency on `core`.

Yes, the BFL module is opaque to the specific boolean predicates. The inference proceeds exactly as you said. The feature synthesizer is responsible for providing the specific predicates -- these may contain integer constants, but we do not currently support synthesis over reals.

**Comment by aastorg2** [comment]
Hello Saswat,

I decided to use your tool within docker as opposed to interfacing with it through windows.
I've been toying around with the test files, in particular, Runner.ml and Test_VPIE.ml. I mostly care about the learnVPreCond function.

(1) I am running into some problems understanding how things work but (2) I may have also found some problems.
For example, in line 20([here](https://github.com/SaswatPadhi/LoopInvGen/blob/master/test/Test_VPIE.ml#L20)) 

would you say there is a bug in the `equivalence_counter_example` function 
(1)
I believe this function is checking the validity of a => b && b =>a by asking z3 if  not (a => b && b =>a) is unsat?
I don't believe the implementation at ZProc.ml ([here](https://github.com/SaswatPadhi/LoopInvGen/blob/master/src/ZProc.ml#L134)) is precisely doing that.

Instead, it should be the function below:

let equivalence_counter_example ?(eval_term = "true") ?(db = [])(z3 : t)
                                (a : string) (b : string) : model option =
  sat_model_for_asserts z3 ~eval_term
                        ~db: (("(assert (not (and (=> " ^ a ^ " " ^ b ^") (=> " ^ b ^ " " ^ a ^"))))") :: db)

**Comment by SaswatPadhi** [comment]
Hello Angello,

Sorry about the late response. I was travelling for the past week.

Thanks for pointing this out! The current implementation for `equivalence_counter_example` definitely looks buggy. Although, it wasn't being used within LoopInvGen but just within the unit tests. I should take a pass over the unit tests soon, quite a few of them are broken due to various code changes.

I think for the VPIE unit test, we can re use the `implication_counter_example`, and don\'t require the `equivalence_counter_example`. It should be enough to check if the inferred precondition implies the required predicate.

**Comment by aastorg2** [comment]
Thanks for the response! Also, thanks for adding the sample project `App`.
I am new to Ocaml and I was struggling to interface with the tool.

I went ahead and added my own example(attached
[samplePIESnippet.txt]   (https://github.com/SaswatPadhi/LoopInvGen/files/2550513/samplePIESnippet.txt))to App.ml

and I have the following questions with the first one being the most important.

1) How do I write a job where the function takes as input a stack or queue. From looking at Value.ml, it seems bool and int are the only supported types.
    
    fun [ Value.List l ] [Value.Int x] -> Value.List (func body)  --> wouldn't work
  
   1a) Assuming the above can be done,  instead  of giving the PIE.learnPreCond function 
test cases with a concrete list such as:  `test 1: [  [1 ; 2] ; 5  ]` where [1 ; 2] is a list containing integers `1` and `2`
I would like to give the learnPreCond function test cases that are an  abstraction of the list. 
For example:
`test 1: [  [true ; 2] ; 5  ]`  where true represent the valuation of some function on l (check if l contains some integer) and 2 represent the head of the list. Obviously, these function would have to be features as well and the representation of the list always has the same format 
`[Contains l ,n ; head l]`. 
More or less, you can say that for non-primitive type the test cases are evaluations of functions on members of these types.

2) I enabled the logging features and added some logging calls of my own, you can see the output below for the snippet I attached:
   2a) Could give me a instruction  to also output the various clauses BLF considers(the enumeration step)  and also output the clauses that are pruned in the algorithm ( those incosistent with atleast 1 positive examples;  those that do not evaluate to false on any negative example )

2018-11-05 21:07:05.666311Z [info ]: RECORD=========================================================================
2018-11-05 21:07:05.666320Z [info ]: New PI task with 2 POS + 1 NEG tests
2018-11-05 21:07:05.666334Z [debug]: Invoking synthesizer with LIA logic.
                                          Conflict group (x :Int , y :Int , u1 :Int):
                                            POS (2):
                                              (20 , 20 , 20)
                                              (10 , 10 , 10)
                                            NEG (1):
                                              (4611686018427387903 , 1 , 0)
2018-11-05 21:07:05.666427Z [debug]: Running enumerative synthesis:
2018-11-05 21:07:05.666438Z [info ]: init explored: 0
2018-11-05 21:07:05.666444Z [info ]: init rejected: 0
2018-11-05 21:07:05.666452Z [debug]: Loaded Constants: [0; 1; false; true]
2018-11-05 21:07:05.666460Z [debug]: Arguments: x,y,u1
2018-11-05 21:07:05.666463Z [debug]:   > Now checking (@ size 1): false
2018-11-05 21:07:05.666467Z [debug]:   > Now checking (@ size 1): true
2018-11-05 21:07:05.666474Z [debug]:   > Now checking (@ size 3): (<= 0 u1)
2018-11-05 21:07:05.666480Z [debug]:   > Now checking (@ size 3): (<= 0 y)
2018-11-05 21:07:05.666486Z [debug]:   > Now checking (@ size 3): (<= 0 x)
2018-11-05 21:07:05.666492Z [debug]:   > Now checking (@ size 3): (<= 1 u1)
2018-11-05 21:07:05.666500Z [debug]:   # Explored 18 expressions (14 rejections)
2018-11-05 21:07:05.666505Z [debug]:   # Solution (@ size 3): (<= 1 u1)
2018-11-05 21:07:05.666510Z [debug]:   # Constraints: ()
2018-11-05 21:07:05.666515Z [debug]: Synthesized feature:
                                              (<= 1 u1)
2018-11-05 21:07:05.666523Z [debug]: Attempting BFL with K = 1
 

thanks!
